// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wasla_Backend.Data;

#nullable disable

namespace Wasla_Backend.data
{
    [DbContext(typeof(Context))]
    [Migration("20260516183551_updateRestaurantModel")]
    partial class updateRestaurantModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BirthDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountViolations")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("IsCompleteRegistration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("lastSeen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Wasla_Backend.Models.BaseModel.BaseBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceProviderType")
                        .HasColumnType("int");

                    b.Property<int>("baseBookingStatus")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("BaseBookings", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Wasla_Backend.Models.BaseModel.BaseService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("BaseServices", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Wasla_Backend.Models.ChatModel.Chat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("deletedByReceiverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletedBySenderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("receiverDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("receiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("senderDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("senderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("receiverId");

                    b.HasIndex("senderId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ChatModel.ChatMessage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("audio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("chatId")
                        .HasColumnType("int");

                    b.Property<string>("fileJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isEdited")
                        .HasColumnType("bit");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.Property<bool>("isSent")
                        .HasColumnType("bit");

                    b.Property<string>("messageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("readAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("receiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("chatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ContactUs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("Wasla_Backend.Models.DoctorSpecialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("DoctorSpecializations");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Driver.RideDispatchJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RideDispatchJobs");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Favourites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GeneralModel.Banner", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GeneralModel.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GeneralModel.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PaymobOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymobTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceProviderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("entityId")
                        .HasColumnType("int");

                    b.Property<int>("entityType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ResidentIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("residentIdentities");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Cart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("residentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("restaurantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("residentId");

                    b.HasIndex("restaurantId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.CartItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cartId")
                        .HasColumnType("int");

                    b.Property<int>("menuItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("cartId");

                    b.HasIndex("menuItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.MenuItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("categoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("discountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("preparationTime")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("restaurantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.HasIndex("restaurantId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.MenuItemCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("restaurantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("restaurantId");

                    b.ToTable("MenuItemCategories");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("deliveryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("paymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("paymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("paymobOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("residentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("restaurantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("transactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("residentId");

                    b.HasIndex("restaurantId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.OrderItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("menuItemId")
                        .HasColumnType("int");

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("menuItemId");

                    b.HasIndex("orderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Reservations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberOfPersons")
                        .HasColumnType("int");

                    b.Property<DateOnly>("reservationDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("reservationTime")
                        .HasColumnType("time");

                    b.Property<string>("restaurantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("restaurantId");

                    b.HasIndex("userId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.RestaurantCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("RestaurantCategories");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ServiceDay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("dayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("end")
                        .HasColumnType("time");

                    b.Property<bool>("isBooking")
                        .HasColumnType("bit");

                    b.Property<int>("serviceId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("start")
                        .HasColumnType("time");

                    b.HasKey("id");

                    b.HasIndex("serviceId");

                    b.ToTable("ServiceDay");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Reaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("reactionType")
                        .HasColumnType("int");

                    b.Property<int>("targetId")
                        .HasColumnType("int");

                    b.Property<int>("targetType")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("targetId");

                    b.HasIndex("userId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("targetId")
                        .HasColumnType("int");

                    b.Property<int>("targetType")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("targetId");

                    b.HasIndex("userId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Social", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("isHidden")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Socials");

                    b.HasDiscriminator().HasValue("Social");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Wasla_Backend.Models.UserEvent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("eventType")
                        .HasColumnType("int");

                    b.Property<string>("serviceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("serviceProviderId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Admin", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ApplicationUser");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.Resident", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ApplicationUser");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Resident", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.ServiceProvider", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ApplicationUser");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.ToTable("serviceProvider");
                });

            modelBuilder.Entity("Wasla_Backend.Models.SuperAdmin", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ApplicationUser");

                    b.ToTable("SuperAdmins", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.Booking", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.BaseModel.BaseBooking");

                    b.Property<int>("bookingStatus")
                        .HasColumnType("int");

                    b.Property<int>("bookingType")
                        .HasColumnType("int");

                    b.Property<string>("imagesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isPaymentOnline")
                        .HasColumnType("bit");

                    b.Property<int>("newDayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("newEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("newStart")
                        .HasColumnType("time");

                    b.Property<int>("serviceDayId")
                        .HasColumnType("int");

                    b.Property<string>("serviceProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("serviceDayId");

                    b.ToTable("DoctorBookings", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.Driver.ride", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.BaseModel.BaseBooking");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DropOffPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DropoffLatitude")
                        .HasColumnType("float");

                    b.Property<double>("DropoffLongitude")
                        .HasColumnType("float");

                    b.Property<string>("PickUpPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("float");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasIndex("DriverId");

                    b.ToTable("Rides", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.GymBooking", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.BaseModel.BaseBooking");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<string>("GymId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GymServiceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsQrUsed")
                        .HasColumnType("bit");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("QrUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<bool>("isPaymentOnline")
                        .HasColumnType("bit");

                    b.HasIndex("GymId");

                    b.HasIndex("ServiceId");

                    b.ToTable("GymBookings", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.technician.TechnicianBooking", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.BaseModel.BaseBooking");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Specialty")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("TechnicianId");

                    b.ToTable("TechnicianBookings", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.Package", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.BaseModel.BaseService");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.Service", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.BaseModel.BaseService");

                    b.Property<string>("DoctorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorServices", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Comment", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.Social.Social");

                    b.Property<string>("file")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("postId")
                        .HasColumnType("int");

                    b.HasIndex("postId");

                    b.HasDiscriminator().HasValue("Comment");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Post", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.Social.Social");

                    b.Property<string>("fileJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Post");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Doctor", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ServiceProvider");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<double>("GraduationYear")
                        .HasColumnType("float");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<string>("UniversityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hospitalname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberOfpatients")
                        .HasColumnType("int");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.Driver.Driver", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ServiceProvider");

                    b.Property<string>("CarImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverFilesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverStatus")
                        .HasColumnType("int");

                    b.Property<int>("DrivingExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("TripsCount")
                        .HasColumnType("int");

                    b.Property<int>("VehicleColor")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleType")
                        .HasColumnType("int");

                    b.ToTable("Driver", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.Gym", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ServiceProvider");

                    b.Property<string>("imagesJson")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("phones")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Gym", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Restaurant", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ServiceProvider");

                    b.Property<string>("gallery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAvalibale")
                        .HasColumnType("bit");

                    b.Property<int?>("restaurantCategoryId")
                        .HasColumnType("int");

                    b.HasIndex("restaurantCategoryId");

                    b.ToTable("Restaurant", (string)null);
                });

            modelBuilder.Entity("Wasla_Backend.Models.technician.Technician", b =>
                {
                    b.HasBaseType("Wasla_Backend.Models.ServiceProvider");

                    b.Property<string>("DocumentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("Specialty")
                        .HasColumnType("int");

                    b.ToTable("Technicians", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.ApplicationRole", b =>
                {
                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "RoleName", b1 =>
                        {
                            b1.Property<string>("ApplicationRoleId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("RoleName_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("RoleName_English");

                            b1.HasKey("ApplicationRoleId");

                            b1.ToTable("AspNetRoles");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationRoleId");
                        });

                    b.Navigation("RoleName")
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.BaseModel.BaseBooking", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Wasla_Backend.Models.BaseModel.BaseService", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "ServiceProvider")
                        .WithMany()
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ChatModel.Chat", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "receiver")
                        .WithMany()
                        .HasForeignKey("receiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "sender")
                        .WithMany()
                        .HasForeignKey("senderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("receiver");

                    b.Navigation("sender");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ChatModel.ChatMessage", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ChatModel.Chat", "Chat")
                        .WithMany("messages")
                        .HasForeignKey("chatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Wasla_Backend.Models.DoctorSpecialization", b =>
                {
                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "Specialization", b1 =>
                        {
                            b1.Property<int>("DoctorSpecializationId")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Specialization_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Specialization_English");

                            b1.HasKey("DoctorSpecializationId");

                            b1.ToTable("DoctorSpecializations");

                            b1.WithOwner()
                                .HasForeignKey("DoctorSpecializationId");
                        });

                    b.Navigation("Specialization")
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Favourites", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "ServiceProvider")
                        .WithMany()
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GeneralModel.Payment", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla_Backend.Models.BaseModel.BaseService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "ServiceProvider")
                        .WithMany()
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Resident");

                    b.Navigation("Service");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Cart", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Resident", "resident")
                        .WithMany()
                        .HasForeignKey("residentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.Restaurant.Restaurant", "restaurant")
                        .WithMany()
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("resident");

                    b.Navigation("restaurant");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.CartItem", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Restaurant.Cart", "cart")
                        .WithMany("items")
                        .HasForeignKey("cartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.Restaurant.MenuItem", "menuItem")
                        .WithMany()
                        .HasForeignKey("menuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cart");

                    b.Navigation("menuItem");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.MenuItem", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Restaurant.MenuItemCategory", "category")
                        .WithMany("items")
                        .HasForeignKey("categoryId");

                    b.HasOne("Wasla_Backend.Models.Restaurant.Restaurant", "restaurant")
                        .WithMany("items")
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "name", b1 =>
                        {
                            b1.Property<int>("MenuItemid")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name_English");

                            b1.HasKey("MenuItemid");

                            b1.ToTable("MenuItems");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemid");
                        });

                    b.Navigation("category");

                    b.Navigation("name")
                        .IsRequired();

                    b.Navigation("restaurant");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.MenuItemCategory", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Restaurant.Restaurant", "restaurant")
                        .WithMany("categories")
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "name", b1 =>
                        {
                            b1.Property<int>("MenuItemCategoryid")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name_English");

                            b1.HasKey("MenuItemCategoryid");

                            b1.ToTable("MenuItemCategories");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemCategoryid");
                        });

                    b.Navigation("name")
                        .IsRequired();

                    b.Navigation("restaurant");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Order", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Resident", "resident")
                        .WithMany()
                        .HasForeignKey("residentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.Restaurant.Restaurant", "restaurant")
                        .WithMany()
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("resident");

                    b.Navigation("restaurant");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.OrderItem", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Restaurant.MenuItem", "menuItem")
                        .WithMany()
                        .HasForeignKey("menuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.Restaurant.Order", "order")
                        .WithMany("items")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menuItem");

                    b.Navigation("order");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Reservations", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Restaurant.Restaurant", "restaurants")
                        .WithMany()
                        .HasForeignKey("restaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.Resident", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("restaurants");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.RestaurantCategory", b =>
                {
                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "name", b1 =>
                        {
                            b1.Property<int>("RestaurantCategoryid")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name_English");

                            b1.HasKey("RestaurantCategoryid");

                            b1.ToTable("RestaurantCategories");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantCategoryid");
                        });

                    b.Navigation("name")
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Reviews", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Reviews")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ServiceDay", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Service", "service")
                        .WithMany("ServiceDays")
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("service");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Reaction", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Social.Social", "target")
                        .WithMany()
                        .HasForeignKey("targetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("target");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Report", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Social.Social", "target")
                        .WithMany()
                        .HasForeignKey("targetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("target");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Social", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Wasla_Backend.Models.UserEvent", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", "serviceProvider")
                        .WithMany()
                        .HasForeignKey("serviceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("serviceProvider");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Admin", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Resident", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Resident", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.ServiceProvider", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.ServiceProvider", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.SuperAdmin", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.SuperAdmin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Booking", b =>
                {
                    b.HasOne("Wasla_Backend.Models.BaseModel.BaseBooking", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Booking", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.ServiceDay", "serviceDay")
                        .WithMany()
                        .HasForeignKey("serviceDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("serviceDay");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Driver.ride", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Driver.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.HasOne("Wasla_Backend.Models.BaseModel.BaseBooking", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Driver.ride", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.GymBooking", b =>
                {
                    b.HasOne("Wasla_Backend.Models.GymModel.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.BaseModel.BaseBooking", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.GymModel.GymBooking", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.GymModel.Package", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Wasla_Backend.Models.technician.TechnicianBooking", b =>
                {
                    b.HasOne("Wasla_Backend.Models.BaseModel.BaseBooking", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.technician.TechnicianBooking", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.technician.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.Package", b =>
                {
                    b.HasOne("Wasla_Backend.Models.BaseModel.BaseService", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.GymModel.Package", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "Description", b1 =>
                        {
                            b1.Property<int>("PackageId")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description_English");

                            b1.HasKey("PackageId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "Name", b1 =>
                        {
                            b1.Property<int>("PackageId")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name_English");

                            b1.HasKey("PackageId");

                            b1.ToTable("Packages");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Service", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Doctor", null)
                        .WithMany("services")
                        .HasForeignKey("DoctorId");

                    b.HasOne("Wasla_Backend.Models.BaseModel.BaseService", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Service", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "description", b1 =>
                        {
                            b1.Property<int>("ServiceId")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("description_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("description_English");

                            b1.HasKey("ServiceId");

                            b1.ToTable("DoctorServices");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.OwnsOne("Wasla_Backend.Helpers.Localization.MultilingualText", "serviceName", b1 =>
                        {
                            b1.Property<int>("ServiceId")
                                .HasColumnType("int");

                            b1.Property<string>("Arabic")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("serviceName_Arabic");

                            b1.Property<string>("English")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("serviceName_English");

                            b1.HasKey("ServiceId");

                            b1.ToTable("DoctorServices");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.Navigation("description");

                    b.Navigation("serviceName");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Comment", b =>
                {
                    b.HasOne("Wasla_Backend.Models.Social.Post", "post")
                        .WithMany("comments")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("post");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Doctor", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.DoctorSpecialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Driver.Driver", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Driver.Driver", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.GymModel.Gym", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.GymModel.Gym", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Restaurant", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.Restaurant.Restaurant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla_Backend.Models.Restaurant.RestaurantCategory", "restaurantCategory")
                        .WithMany()
                        .HasForeignKey("restaurantCategoryId");

                    b.Navigation("restaurantCategory");
                });

            modelBuilder.Entity("Wasla_Backend.Models.technician.Technician", b =>
                {
                    b.HasOne("Wasla_Backend.Models.ServiceProvider", null)
                        .WithOne()
                        .HasForeignKey("Wasla_Backend.Models.technician.Technician", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla_Backend.Models.ChatModel.Chat", b =>
                {
                    b.Navigation("messages");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Cart", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.MenuItemCategory", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Order", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("Wasla_Backend.Models.ServiceProvider", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Service", b =>
                {
                    b.Navigation("ServiceDays");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Social.Post", b =>
                {
                    b.Navigation("comments");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Doctor", b =>
                {
                    b.Navigation("services");
                });

            modelBuilder.Entity("Wasla_Backend.Models.Restaurant.Restaurant", b =>
                {
                    b.Navigation("categories");

                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
